### ISSUE TITLE
esl-shuffle -A fails, complaining of "no such option --boot"

### ISSUE THREAD

**Issue by cryptogenomicon** [EddyRivasLab/easel#24]
`esl-shuffle -A` (alignment shuffling and bootstrapping) fails, saying `no such option --boot`. Problem appears to be that the code is testing for `--boot`, but the option is `-b`.

**Comment by ppgardne** [comment]
Have just done a pull and am getting the same error:
```
./miniapps/esl-shuffle  -A  ~/inst/rscape/tutorial/ar14.sto
no such option --boot
```
Can you replicate, or do you need more info?

**Comment by cryptogenomicon** [comment]
Master (release) branch still has the bug because we haven't done a HMMER or Infernal release since committing the fix. A new HMMER3 release is coming soon - either hang out for that, or (better option!) build the Easel develop branch, which is very stable these days.
```
    git checkout develop
    autoconf
    ./configure; make
```

**Comment by ppgardne** [comment]
That works a treat. Thanks! 
New HMMER3, exciting!
