### ISSUE TITLE
esl-fetch fails on Metaclust database

### ISSUE THREAD

**Issue by rakeshr10** [EddyRivasLab/easel#27]
I have been trying to use esl-sfetch to extract sequences from Metaclust database (https://metaclust.mmseqs.org/2018_06/). Since it requires creating SSI index file I was trying to create one but I get this output

Creating SSI index for metaclust_nr.fasta...    sort: write failed: /tmp/sortVWzazq: No space left on device

Failed to write keys to ssi file metaclust_nr.fasta.ssi:
  external sort of primary keys failed

Moreover I see these SSI files being created.

-rw-r--r--. 1 rakesh sali 241G Jun 22 05:03 metaclust_nr.fasta
-rw-r--r--. 1 rakesh sali    0 Dec 13 03:14 metaclust_nr.fasta.ssi.2
-rw-r--r--. 1 rakesh sali  71G Dec 13 04:04 metaclust_nr.fasta.ssi.1

Now when I use esl-seftch to extract sequences I get this output.

grep -v "^#" Cop9_msa.domtblout | awk '{print $1"/"$20"-"$21, $20, $21, $1}' | /home/rakesh/WORK/Softwares/Sequence_Alignment/hmmer3.2source/hmmer-3.2.1/easel/miniapps/esl-sfetch -Cf /salilab/park3/rakesh/Databases/metaclust/metaclust_nr.fasta - > yest
Failed to open SSI index

How to resolve this ?

**Comment by cryptogenomicon** [comment]
You ran out of space in `/tmp` (this is what the`no space left on device` error message is telling you).
You can set your `${TMPDIR}` env variable to a different filesystem where you have plenty of available disk space, and try again. 
For large indices, `esl-sfetch --index` needs to write some large temporary files and sort on disk.
