### ISSUE TITLE
Solaris: GCC bug

### ISSUE THREAD

**Issue by sjaenick** [EddyRivasLab/easel#3]
easel is affected by

  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=40411

on Solaris, which makes utest_IsReal fail for "+0xabc.defp-12".

I'll try to come up with a workaround (or at least a configure check).

**Comment by cryptogenomicon** [comment]
Good, let me know. But why does it fail there, in particular? Solaris strtod() isn't C99 compliant?
