### ISSUE TITLE
esl_fprintf and similar functions

### ISSUE THREAD

**Issue by horta** [EddyRivasLab/easel#41]
I like the idea of having fprintf/printf etc. alternatives that does the error checking on the spot. This is IMHO the proper approach when there is nothing that the caller can do when that kind of error happens.

However, the [current implementation](https://github.com/EddyRivasLab/easel/blob/82b54a96f92f7210ea17a2057a636099fdb3f72d/easel.c#L750) has a flaw: the call to ESL_EXCEPTION_SYS macro will record the same `__FILE__` and `__LINE__` ([ESL_EXCEPTION_SYS](https://github.com/EddyRivasLab/easel/blob/82b54a96f92f7210ea17a2057a636099fdb3f72d/easel.h#L82)) everywhere `esl_printf` is being used.

Shall we propose MACRO replacement for those functions?

**Comment by cryptogenomicon** [comment]
Yes, that sounds like a better idea. (Not a high priority though.)
