### ISSUE TITLE
esl-reformat mixed gaps error

### ISSUE THREAD

**Issue by marceloqla** [EddyRivasLab/easel#42]
Hello, when converting a Pfam file containing mixed Gaps to the a2m format using esl-reformat I noticed that gaps as dots were ignored and not included in the final file. Is this an intended feature?

Sorry for bothering and thanks for the attention

**Comment by cryptogenomicon** [comment]
That's how ('dotless') A2M format works - no dots. See HMMER Userguide for a description of A2M format, or [https://compbio.soe.ucsc.edu/a2m-desc.html](https://compbio.soe.ucsc.edu/a2m-desc.html). If you want aligned FASTA instead, that's `afa`.
