### ISSUE TITLE
Set tmp directory for esl-sfetch

### ISSUE THREAD

**Issue by arglog** [EddyRivasLab/easel#53]
Hi easel team,

I'm using esl-sfetch to build index for a large fasta file ([metaclust_nr.fasta](https://metaclust.mmseqs.org/current_release/), 241G). I used the following command
```
esl-sfetch --index metaclust_nr.fasta
```
I got the following error. It seems there is no space available under `/tmp`
```
Creating SSI index for metaclust_nr.fasta...    sort: write failed: /tmp/sort5sUUWF: No space left on device

Failed to write keys to ssi file metaclust_nr.fasta.ssi:
  external sort of primary keys failed
```
As the `/tmp` on my machine wasn't mounted to a large drive, I'm wondering if I can specify another path to be used as the temp directory, so that esl-sfetch has enough space to write? I didn't find any argument for this purpose in `esl-sfetch -h`. Is there any walkaround?

Thanks!

**Comment by cryptogenomicon** [comment]
Yes, you can set ${TMPDIR} or ${TMP} in your shell environment to be the path to any directory you want. This is the usual UNIX/POSIX behavior, I believe!

**Comment by arglog** [comment]
Yes, `export TMPDIR=/path/to/tmp` solves the problem! Thanks!
