### ISSUE TITLE
esl_mixdchlet-utest fails when compiled with --enable-debugging=3

### ISSUE THREAD

**Issue by npcarter** [EddyRivasLab/easel#58]
On the develop branch (at least, haven't checked others), if Easel is configured with --enable-debugging=3, the mixdchlet utest crashes with "Error in `../esl_mixdchlet_utest': free(): invalid pointer: 0x0000000002098a70 ***".  

I first encountered this while testing the ARM port code, but replicated it on x86 Odyssey machines, so it looks like it's a general problem, not an ARM bug.

**Comment by cryptogenomicon** [comment]
Thanks, should be fixed now.

**Comment by npcarter** [comment]
You're welcome.  I tripped over that while testing the ARM code.

-Nick
