### ISSUE TITLE
issue while installing HMMER

### ISSUE THREAD

**Issue by mohankrishnas777** [EddyRivasLab/easel#64]
Running Easel test suite...

make[2]: ./../devkit/sqc: No such file or directory
make[2]: *** [Makefile:34: check] Error 127
make[1]: *** [Makefile:537: check] Error 2
make: *** [Makefile:116: check] Error 2

HP@DESKTOP-T2RTKVR /home/user/hmmer-3.3.2

How to remove that errors

**Comment by mohankrishnas777** [comment]
HP@DESKTOP-T2RTKVR /home/user/hmmer-3.3.2
$ make check
     SUBDIR easel
     SUBDIR miniapps
     SUBDIR libdivsufsort
     SUBDIR src
     SUBDIR impl_sse
     SUBDIR impl_sse
     SUBDIR easel
     SUBDIR miniapps
     SUBDIR testsuite

Running Easel test suite...

make[2]: ./../devkit/sqc: No such file or directory
make[2]: *** [Makefile:34: check] Error 127
make[1]: *** [Makefile:537: check] Error 2
make: *** [Makefile:116: check] Error 2

HP@DESKTOP-T2RTKVR /home/user/hmmer-3.3.2
$

**Comment by cryptogenomicon** [comment]
That might happen if you don't have Perl installed. HMMER uses some Perl and Python scripts, especially in its automated tests; check that you have both installed.
