### ISSUE TITLE
Error in extracting the hmmsearch hits by esl-sfetch -f

### ISSUE THREAD

**Issue by GokilavaniThangavel** [EddyRivasLab/easel#65]
I am trying to look extract my hits as a result of hmmsearch in my desired database.

First I saved my output of hmmsearch as a fasta file

indexed my own database by using esl-sfetch --index dataset

Then I tried extracting my hmmsearch hits in the database
for instance 
esl-sfetch -f dataset hmmserach_output.fasta > extraction_output.fasta

But I repeatedly get an error message, "seq query: not found in the SSI index for file"

When I checked a single hit manually from hmmsearch, in my database, the query is found. So I am sure the hits are present in the database. But I could not do it successfully through esl-sfetch

Any idea about what is happening?

Thanks in advance

**Comment by cryptogenomicon** [comment]
If I understand right, you're trying to give the main output of hmmsearch directly to esl-sfetch. That won't work. See the documentation for esl-sfetch for the format of the inputs it takes.
