### ISSUE TITLE
`esl_sq_Copy` doesn't copy `tax_id` attribute

### ISSUE THREAD

**Issue by valentynbez** [EddyRivasLab/easel#68]
A `tax_id` attribute of `sq` object is not copied during `esl_sq_Copy` and `-1` is automatically assigned as a value.
https://github.com/EddyRivasLab/easel/blob/281c81377595ef781dff962d9572240406a5e364/esl_sq.c#L265-L352

**Comment by cryptogenomicon** [comment]
Yes, that's fine, because `tax_id` is unused right now... a placeholder for future development. There are various other places in the code that would have to be changed if/when we start using it.

**Comment by althonos** [comment]
Thanks for the confirmation @cryptogenomicon.
