### ISSUE TITLE
CT to WUSS format convertion

### ISSUE THREAD

**Issue by mkazanov** [EddyRivasLab/easel#71]
Dear easel developers,

Is it possible to convert CT format file to WUSS format file using easel?
If so, what command I should execute?

Thanks

**Comment by cryptogenomicon** [comment]
Easel has internal support for doing the conversion (i.e. we have function calls, `esl_ct2wuss()` and `esl_ct2simplewuss()`), but I don't think we have these hooked up to anything in any of our programs or Easel miniapps. If you know some C, it'd be pretty straightforward to write a little program to make the right call.

**Comment by mkazanov** [comment]
Dear Sean, thank you for the answer!
I had a look into these functions and wondering what is the input `int *ct`?
I suspect that it should be CT file, but why it is `int` and not `string`? If it is just an int array, what column out of six CT-file' columns is in this array? Possibly the 5-th column with the information on connectivity?

**Comment by mkazanov** [comment]
I figured out using comments before the functions.
