### ISSUE TITLE
HMMER-make check fail

### ISSUE THREAD

**Issue by VimaxXAAS** [EddyRivasLab/easel#72]
Running Easel test suite...

make[2]: ./../devkit/sqc: No such file or directory
make[2]: *** [Makefile:34: check] Error 127
make[1]: *** [Makefile:537: check] Error 2
make: *** [Makefile:116: check] Error 2

HP@DESKTOP-T2RTKVR /home/user/hmmer-3.3.2

How to solve this error

**Comment by cryptogenomicon** [comment]
Do you have perl, in `/usr/bin/perl`?

**Comment by VimaxXAAS** [comment]
No.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cryptogenomicon** [comment]
The test suite scripts require perl (and python3), but HMMER itself does not. You can safely skip the `make check`.

**Comment by VimaxXAAS** [comment]
Problem is "hmmbuild" command not found error

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cryptogenomicon** [comment]
I'll need more information. What exactly did you type as your commands, and what exactly was the output, and on what kind of platform/operating system?

**Comment by VimaxXAAS** [comment]
[cid:66dbe196-9e5e-4dda-b2eb-e43d07340299]
________________________________

**Comment by VimaxXAAS** [comment]
[cid:f33f2ce7-1c9e-4e09-a85c-800b59b49b3c]
________________________________

**Comment by cryptogenomicon** [comment]
You seem to be trying to send some sort of link(s), which don't work. I need to see text for your commands, your output, and your platform/OS.

**Comment by VimaxXAAS** [comment]
I am using a window 11 pro. I am trying to use Hmmer search to screen some genes. I am facing this error. I used Cygwin64 for Hmmer-3.4

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cryptogenomicon** [comment]
Sorry, you still haven't given me the information I need to understand the error you're seeing. What did you type, and what output did you get? You initially said that `make check` failed, and you said you don't have perl, so `make check` is going to fail - and you don't need it, and can skip it. Now you say that you get an `hmmbuild not found` error, and I'm asking what you did before you got that error, and exactly what it output.

It may be as simple as just understanding how to install and run programs in Windows 11; I can't help you with that, but that'll be something general that you can figure out elsewhere. In Linux and OS/X, if you install a program in a directory (say, `hmmbuild` in `/usr/local/bin`) then you either need to have `/usr/local/bin` in your `${PATH}` so you can run it by typing `hmmbuild`, or you need to specify the path yourself, typing `/usr/local/bin/hmmbuild`.

**Comment by VimaxXAAS** [comment]
[cid:f5a6f2de-7e08-4aa9-a25c-d65e4f6ced38] this is more detailed. i am using window 11. can you help me to install "pearl"
________________________________
